alter table datasource_info modify column `data_type_code` int(11) not null default 0 comment '数据源类型编码';

-- 新增 Kyuubi 数据源类型
INSERT INTO `datasource_type` (id, data_type, data_classify_id, weight, img_url, sorted, invisible, is_deleted) values (91, 'Kyuubi', 4, 0.0, 'Kyuubi.png', 2100, 0, 0);
INSERT INTO `datasource_form_field` (id, name, label, widget, required, invisible, default_value, place_hold, request_api, is_link, valid_info, tooltip, style, regex, type_version, is_deleted, options) values (397, 'jdbcUrl', 'JDBC URL', 'Input', 1, 0, '', 'jdbc:kyuubi://host:port/schema', null, 0, '{"regex":{"message":"JDBC URL格式不符合规则!"}}', null, null, '/jdbc:kyuubi:\/\/(.)+/', 'Kyuubi', 0, '');
INSERT INTO `datasource_form_field` (id, name, label, widget, required, invisible, default_value, place_hold, request_api, is_link, valid_info, tooltip, style, regex, type_version, is_deleted, options) values (398, 'username', '用户名', 'Input', 0, 0, '', null, null, 0, null, null, null, null, 'Kyuubi', 0, '');
INSERT INTO `datasource_form_field` (id, name, label, widget, required, invisible, default_value, place_hold, request_api, is_link, valid_info, tooltip, style, regex, type_version, is_deleted, options) values (399, 'password', '密码', 'Password', 0, 0, '', null, null, 0, null, null, null, null, 'Kyuubi', 0, '');
INSERT INTO `datasource_form_field` (id, name, label, widget, required, invisible, default_value, place_hold, request_api, is_link, valid_info, tooltip, style, regex, type_version, is_deleted, options) values (400, 'defaultFS', 'defaultFS', 'Input', 1, 0, '', 'hdfs://host:port', null, 1, null, '注意结尾不带/', null, null, 'Kyuubi', 0, '');
INSERT INTO `datasource_form_field` (id, name, label, widget, required, invisible, default_value, place_hold, request_api, is_link, valid_info, tooltip, style, regex, type_version, is_deleted, options) values (401, 'hadoopConfig', '高可用配置', 'TextAreaWithCopy',0,0, null, '{"dfs.nameservices":"defaultDfs","dfs.ha.namenodes.defaultDfs":"namenode1","dfs.namenode.rpc-address.defaultDfs.namenode1":"","dfs.client.failover.proxy.provider.defaultDfs":"org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider"}', null, 0, '', '', null, null, 'Kyuubi', 0, '');
INSERT INTO `datasource_form_field` (id, name, label, widget, required, invisible, default_value, place_hold, request_api, is_link, valid_info, tooltip, style, regex, type_version, is_deleted, options) values (402, 'defaultResultPath', '查询结果保存路径', 'Input', 1, 0, null, '/taier/select_res/', null, 0, null, '注意开头结束都是/', null, null, 'Kyuubi', 0, '');
INSERT INTO dict (dict_code, dict_name, dict_value, dict_desc, type, sort, data_type, depend_name, is_default, is_deleted) values ('28', 'Kyuubi', '{"actions":["SAVE_TASK","RUN_TASK","STOP_TASK","SUBMIT_TASK","OPERATOR_TASK"],"barItem":["task","dependency","task_params","env_params"],"formField":["datasource"],"renderKind":"editor","dataTypeCodes":[1004]}', null, 30, 0, 'STRING', '', 0, 0);


