alter table datasource_info modify column `data_type_code` int(11) not null default 0 comment '数据源类型编码';

-- 新增 Kyuubi 数据源类型
INSERT INTO `datasource_type` (id, data_type, data_classify_id, weight, img_url, sorted, invisible, is_deleted) VALUES (91, 'Kyuubi', 4, 0.0, 'Kyuubi.png', 2100, 0, 0);
INSERT INTO `datasource_form_field` (id, name, label, widget, required, invisible, default_value, place_hold, request_api, is_link, valid_info, tooltip, style, regex, type_version, is_deleted, options) VALUES (397, 'jdbcUrl', 'JDBC URL', 'Input', 1, 0, '', 'jdbc:kyuubi://host:port/schema', null, 0, '{"regex":{"message":"JDBC URL格式不符合规则!"}}', null, null, '/jdbc:kyuubi:\/\/(.)+/', 'Kyuubi', 0, '');
INSERT INTO `datasource_form_field` (id, name, label, widget, required, invisible, default_value, place_hold, request_api, is_link, valid_info, tooltip, style, regex, type_version, is_deleted, options) VALUES (398, 'username', '用户名', 'Input', 0, 0, '', null, null, 0, null, null, null, null, 'Kyuubi', 0, '');
INSERT INTO `datasource_form_field` (id, name, label, widget, required, invisible, default_value, place_hold, request_api, is_link, valid_info, tooltip, style, regex, type_version, is_deleted, options) VALUES (399, 'password', '密码', 'Password', 0, 0, '', null, null, 0, null, null, null, null, 'Kyuubi', 0, '');
INSERT INTO `datasource_form_field` (id, name, label, widget, required, invisible, default_value, place_hold, request_api, is_link, valid_info, tooltip, style, regex, type_version, is_deleted, options) VALUES (400, 'defaultFS', 'defaultFS', 'Input', 1, 0, '', 'hdfs://host:port', null, 1, null, '注意结尾不带/', null, null, 'Kyuubi', 0, '');
INSERT INTO `datasource_form_field` (id, name, label, widget, required, invisible, default_value, place_hold, request_api, is_link, valid_info, tooltip, style, regex, type_version, is_deleted, options) VALUES (401, 'hadoopConfig', '高可用配置', 'TextAreaWithCopy',0,0, null, '{\n"dfs.nameservices": "defaultDfs",\n"dfs.ha.namenodes.defaultDfs": "namenode1",\n"dfs.namenode.rpc-address.defaultDfs.namenode1": "",\n"dfs.client.failover.proxy.provider.defaultDfs": "org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider"\n}', null, 0, '', '高可用模式下的填写规则：\n1、分别要填写：nameservice名称、 namenode名称（多个以逗号分隔）、proxy.provider参数；\n2、所有参数以JSON格式填写；\n3、格式为：\n"dfs.nameservices": "nameservice名称", "dfs.ha.namenodes.nameservice名称": "namenode名称，以逗号分隔", "dfs.namenode.rpc-address.nameservice名称.namenode名称": "", "dfs.namenode.rpc-address.nameservice名称.namenode名称": "", "dfs.client.failover.proxy.provider.\nnameservice名称": "org.apache.hadoop.\nhdfs.server.namenode.ha.\nConfiguredFailoverProxyProvider"\n4、详细参数含义请参考《帮助文档》或<a href=''http://hadoop.apache.org/docs/r2.7.4/hadoop-project-dist/hadoop-hdfs/HDFSHighAvailabilityWithQJM.html''>Hadoop官方文档</a>', null, null, 'Kyuubi', 0, '');
INSERT INTO `datasource_form_field` (id, name, label, widget, required, invisible, default_value, place_hold, request_api, is_link, valid_info, tooltip, style, regex, type_version, is_deleted, options) VALUES (402, 'defaultResultPath', '查询结果保存路径', 'Input', 1, 0, null, '/taier/select_res/', null, 0, null, '注意开头结束都是/', null, null, 'Kyuubi', 0, '');
INSERT INTO dict (dict_code, dict_name, dict_value, dict_desc, type, sort, data_type, depend_name, is_default, is_deleted) VALUES ('28', 'Kyuubi', '{"actions":["SAVE_TASK","RUN_TASK","STOP_TASK","SUBMIT_TASK","OPERATOR_TASK"],"barItem":["task","dependency","task_params","env_params"],"formField":["datasource"],"renderKind":"editor","dataTypeCodes":[1004]}', null, 30, 0, 'STRING', '', 0, 0);

-- Kyuubi 任务默认参数
INSERT INTO `task_param_template` (id, task_type, task_name, task_version, params) VALUES (19, 28, 'KYUUBI_SPARK_SQL', null, '## Driver程序使用的CPU核数,默认为1\n# spark.driver.cores=1\n\n## Driver程序使用内存大小,默认1g\n# spark.driver.memory=1g\n\n## 对Spark每个action结果集大小的限制，最少是1M，若设为0则不限制大小。\n## 若Job结果超过限制则会异常退出，若结果集限制过大也可能造成OOM问题，默认1g\n# spark.driver.maxResultSize=1g\n\n## 启动的executor的数量，默认为1\n# spark.executor.instances=1\n\n## 每个executor使用的CPU核数，默认为1\n# spark.executor.cores=1\n\n## 每个executor内存大小,默认1g\n# spark.executor.memory=1g\n\n## spark中所有网络交互的最大超时时间\n# spark.network.timeout=120s\n\n## executor的OffHeap内存，和spark.executor.memory配置使用\n# spark.yarn.executor.memoryOverhead=\n\n## 设置spark sql shuffle分区数，默认200\n# spark.sql.shuffle.partitions=200');
