alter table datasource_info modify column `data_type_code` int(11) not null default 0 comment '数据源类型编码';

-- 新增 Kyuubi 数据源类型
INSERT INTO `datasource_type` (id, data_type, data_classify_id, weight, img_url, sorted, invisible, is_deleted) VALUES (91, 'Kyuubi', 4, 0.0, 'Kyuubi.png', 2100, 0, 0);
INSERT INTO `datasource_form_field` (id, name, label, widget, required, invisible, default_value, place_hold, request_api, is_link, valid_info, tooltip, style, regex, type_version, is_deleted, options) VALUES (397, 'jdbcUrl', 'JDBC URL', 'Input', 1, 0, '', 'jdbc:kyuubi://host:port/schema', null, 0, '{"regex":{"message":"JDBC URL格式不符合规则!"}}', null, null, '/jdbc:kyuubi:\/\/(.)+/', 'Kyuubi', 0, '');
INSERT INTO `datasource_form_field` (id, name, label, widget, required, invisible, default_value, place_hold, request_api, is_link, valid_info, tooltip, style, regex, type_version, is_deleted, options) VALUES (398, 'username', '用户名', 'Input', 0, 0, '', null, null, 0, null, null, null, null, 'Kyuubi', 0, '');
INSERT INTO `datasource_form_field` (id, name, label, widget, required, invisible, default_value, place_hold, request_api, is_link, valid_info, tooltip, style, regex, type_version, is_deleted, options) VALUES (399, 'password', '密码', 'Password', 0, 0, '', null, null, 0, null, null, null, null, 'Kyuubi', 0, '');
INSERT INTO `datasource_form_field` (id, name, label, widget, required, invisible, default_value, place_hold, request_api, is_link, valid_info, tooltip, style, regex, type_version, is_deleted, options) VALUES (400, 'defaultFS', 'defaultFS', 'Input', 1, 0, '', 'hdfs://host:port', null, 1, null, '注意结尾不带/', null, null, 'Kyuubi', 0, '');
INSERT INTO `datasource_form_field` (id, name, label, widget, required, invisible, default_value, place_hold, request_api, is_link, valid_info, tooltip, style, regex, type_version, is_deleted, options) VALUES (401, 'hadoopConfig', '高可用配置', 'TextAreaWithCopy',0,0, null, '{\n"dfs.nameservices": "defaultDfs",\n"dfs.ha.namenodes.defaultDfs": "namenode1",\n"dfs.namenode.rpc-address.defaultDfs.namenode1": "",\n"dfs.client.failover.proxy.provider.defaultDfs": "org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider"\n}', null, 0, '', '高可用模式下的填写规则：\n1、分别要填写：nameservice名称、 namenode名称（多个以逗号分隔）、proxy.provider参数；\n2、所有参数以JSON格式填写；\n3、格式为：\n"dfs.nameservices": "nameservice名称", "dfs.ha.namenodes.nameservice名称": "namenode名称，以逗号分隔", "dfs.namenode.rpc-address.nameservice名称.namenode名称": "", "dfs.namenode.rpc-address.nameservice名称.namenode名称": "", "dfs.client.failover.proxy.provider.\nnameservice名称": "org.apache.hadoop.\nhdfs.server.namenode.ha.\nConfiguredFailoverProxyProvider"\n4、详细参数含义请参考《帮助文档》或<a href=''http://hadoop.apache.org/docs/r2.7.4/hadoop-project-dist/hadoop-hdfs/HDFSHighAvailabilityWithQJM.html''>Hadoop官方文档</a>', null, null, 'Kyuubi', 0, '');
INSERT INTO `datasource_form_field` (id, name, label, widget, required, invisible, default_value, place_hold, request_api, is_link, valid_info, tooltip, style, regex, type_version, is_deleted, options) VALUES (402, 'defaultResultPath', '查询结果保存路径', 'Input', 1, 0, null, '/taier/select_res/', null, 0, null, '注意开头结束都是/', null, null, 'Kyuubi', 0, '');
INSERT INTO dict (dict_code, dict_name, dict_value, dict_desc, type, sort, data_type, depend_name, is_default, is_deleted) VALUES ('28', 'Kyuubi', '{"actions":["SAVE_TASK","RUN_TASK","STOP_TASK","SUBMIT_TASK","OPERATOR_TASK"],"barItem":["task","dependency","task_params","env_params"],"formField":["datasource","queue"],"renderKind":"editor","dataTypeCodes":[1004]}', null, 30, 0, 'STRING', '', 0, 0);

-- Kyuubi 任务默认参数
INSERT INTO `task_param_template` (task_type, task_name, task_version, params) VALUES (28, 'KYUUBI_SPARK_SQL', null, '## Driver程序使用的CPU核数,默认为1\n# spark.driver.cores=1\n\n## Driver程序使用内存大小,默认1g\n# spark.driver.memory=1g\n\n## 对Spark每个action结果集大小的限制，最少是1M，若设为0则不限制大小。\n## 若Job结果超过限制则会异常退出，若结果集限制过大也可能造成OOM问题，默认1g\n# spark.driver.maxResultSize=1g\n\n## 启动的executor的数量，默认为1\n# spark.executor.instances=1\n\n## 每个executor使用的CPU核数，默认为1\n# spark.executor.cores=1\n\n## 每个executor内存大小,默认1g\n# spark.executor.memory=1g\n\n## spark中所有网络交互的最大超时时间\n# spark.network.timeout=120s\n\n## executor的OffHeap内存，和spark.executor.memory配置使用\n# spark.yarn.executor.memoryOverhead=\n\n## 设置spark sql shuffle分区数，默认200\n# spark.sql.shuffle.partitions=200');

-- 新增 flink116
INSERT INTO dict (dict_code, dict_name, dict_value, dict_desc, type, sort, data_type, depend_name, is_default) VALUES ('flink_version', '1.16-on-yarn', '116', null, 1,2, 'INTEGER', '', 0);
INSERT INTO dict (dict_code, dict_name, dict_value, dict_desc, type, sort, data_type, depend_name, is_default) VALUES ('typename_mapping', 'yarn3-hdfs3-flink116', '-115', null, 6, 0, 'LONG', '', 0);
UPDATE dict SET dict_value = '{"HDFS":{"HDFS":"yarn3-hdfs3-hadoop3","FLINK":[{"112":"yarn3-hdfs3-flink112","116":"yarn3-hdfs3-flink116"}],"SPARK":[{"320":"yarn3-hdfs3-spark320"},{"210":"yarn3-hdfs3-spark210"}],"SCRIPT":"yarn3-hdfs3-script"},"YARN":"yarn3"}'
    WHERE dict_value = '{"HDFS": {"HDFS": "yarn3-hdfs3-hadoop3", "FLINK": [{"112": "yarn3-hdfs3-flink112"}], "SPARK": [{"320": "yarn3-hdfs3-spark320"}, {"210": "yarn3-hdfs3-spark210"}], "SCRIPT": "yarn3-hdfs3-script"}, "YARN": "yarn3"}';

-- 同步任务支持选择 flink 版本
UPDATE dict SET dict_value = '{"actions":["SAVE_TASK","RUN_TASK","STOP_TASK","SUBMIT_TASK","OPERATOR_TASK"],"barItem":["task","dependency","task_config","task_params","env_params"],"formField":["createModel","syncModel","componentVersion"],"renderKind":"dataSync","renderCondition":{"key":"createModel","value":0,"renderKind":"editor"},"actionsCondition":{"key":"createModel","value":0,"actions":["CONVERT_TASK","SAVE_TASK","RUN_TASK","STOP_TASK","SUBMIT_TASK","OPERATOR_TASK"]}}'
    WHERE dict_code = '2';
INSERT INTO `task_param_template` (task_type, task_name, task_version, params) VALUES (2, 'SYNC', '116', '## 任务运行方式：\n## per_job:单独为任务创建flink yarn session，适用于低频率，大数据量同步\n## session：多个任务共用一个flink yarn session，适用于高频率、小数据量同步，默认session\n## standalone：多个任务共用一个flink standalone\n## flinkTaskRunMode=per_job\n## per_job模式下jobManager配置的内存大小，默认1024（单位M)\n## jobmanager.memory.mb=1024\n## per_job模式下taskManager配置的内存大小，默认1024（单位M）\n## taskmanager.memory.mb=1024\n## per_job模式下每个taskManager 对应 slot的数量\n## slots=1\n## checkpoint保存时间间隔\n## flink.checkpoint.interval=300000\n## 任务优先级, 范围:1-1000\n## job.priority=10');
INSERT INTO `task_param_template` (task_type, task_name, task_version, params) VALUES (5, 'FlinkSQL', '116', '## 资源相关\nparallelism.default=1\ntaskmanager.numberOfTaskSlots=1\njobmanager.memory.process.size=1g\ntaskmanager.memory.process.size=2g\n\n## 时间相关\n## 设置Flink时间选项，有ProcessingTime,EventTime,IngestionTime可选\n## 非脚本模式会根据Kafka自动设置。脚本模式默认为ProcessingTime\n# pipeline.time-characteristic=EventTime\n\n## Checkpoint相关\n## 生成checkpoint时间间隔（以毫秒为单位），默认:5分钟,注释掉该选项会关闭checkpoint生成\nexecution.checkpointing.interval=5min\n## 状态恢复语义,可选参数EXACTLY_ONCE,AT_LEAST_ONCE；默认为EXACTLY_ONCE\n# execution.checkpointing.mode=EXACTLY_ONCE\n##任务取消后保留hdfs上的checkpoint文件\nexecution.checkpointing.externalized-checkpoint-retention=RETAIN_ON_CANCELLATION\n\n# Flink SQL独有，状态过期时间\ntable.exec.state.ttl=1d\n\nlog.level=INFO\n\n## 使用Iceberg和Hive维表开启\n# table.dynamic-table-options.enabled=true\n\n## Kerberos相关\n# security.kerberos.login.contexts=Client,KafkaClient\n\n\n## 高阶参数\n## 窗口提前触发时间\n# table.exec.emit.early-fire.enabled=true\n# table.exec.emit.early-fire.delay=1s\n\n## 当一个源在超时时间内没有收到任何元素时，它将被标记为临时空闲\n# table.exec.source.idle-timeout=10ms\n\n## 是否开启minibatch\n## 可以减少状态开销。这可能会增加一些延迟，因为它会缓冲一些记录而不是立即处理它们。这是吞吐量和延迟之间的权衡\n# table.exec.mini-batch.enabled=true\n## 状态缓存时间\n# table.exec.mini-batch.allow-latency=5s\n## 状态最大缓存条数\n# table.exec.mini-batch.size=5000\n\n## 是否开启Local-Global 聚合。前提需要开启minibatch\n## 聚合是为解决数据倾斜问题提出的，类似于 MapReduce 中的 Combine + Reduce 模式\n# table.optimizer.agg-phase-strategy=TWO_PHASE\n\n## 是否开启拆分 distinct 聚合\n## Local-Global 可以解决数据倾斜，但是在处理 distinct 聚合时，其性能并不令人满意。\n## 如：SELECT day, COUNT(DISTINCT user_id) FROM T GROUP BY day 如果 distinct key （即 user_id）的值分布稀疏，建议开启\n# table.optimizer.distinct-agg.split.enabled=true\n\n\n## Flink算子chaining开关。默认为true。排查性能问题时会暂时设置成false，但降低性能。\n# pipeline.operator-chaining=true');
UPDATE `task_param_template` SET task_version = '112'
    WHERE task_name = 'SYNC' AND task_version = '1.12';
UPDATE `task_param_template` SET task_version = '112'
    WHERE task_name = 'FlinkSQL' AND task_version = '1.12';


